### ISSUE TITLE
过滤部分文件夹

### ISSUE THREAD

**Issue by valetzx** [ShirasawaSama/CefDetectorX#1]
你好，可不可以添加部分文件夹过滤，扫到我的onedrive直接爆炸了
![image](https://user-images.githubusercontent.com/45054400/204295221-369398fb-0ce2-47e5-8f9e-dab69b8e7125.png)

**Comment by shenjackyuanjie** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by ShirasawaSama** [comment]
0.0.1 已忽略回收站和OneDrive下的文件
