### ISSUE TITLE
Suggestion: rewrite the page using react

### ISSUE THREAD

**Issue by AH-dark** [ShirasawaSama/CefDetectorX#10]
I want to use the React+Electron solution to rewrite the front-end part of this software and ask for your opinion.

React can make software more niubi. (maybe?)

**Comment by ShirasawaSama** [comment]
没这个必要，UI部分其实不到10行代码，其他都是扫描 CEF 类型的逻辑代码。

况且引入 react 之后整个 APP 的构建流程都会变化，现在发布时是不带任何第三方模块的。

https://github.com/ShirasawaSama/CefDetectorX/blob/master/resources/app/index.js#L87

**Comment by AH-dark** [comment]
But it's fun! 😕

**Comment by ShirasawaSama** [comment]
不如添加对 macos 的支持(
