### ISSUE TITLE
Recognize log files as CEF

### ISSUE THREAD

**Issue by SN-Yang** [ShirasawaSama/CefDetectorX#22]
![libcef-issue1](https://user-images.githubusercontent.com/74240568/208622805-122a1b2b-f2d1-4f20-bb34-5fbcd52b2759.png)
![libcef-issue](https://user-images.githubusercontent.com/74240568/208622826-186d4d68-d0bd-4c60-b702-adc814e7357b.png)

**Comment by ShirasawaSama** [comment]
0.1.0已修复
