### ISSUE TITLE
我不理解，一直是0个

### ISSUE THREAD

**Issue by Kx-Y** [ShirasawaSama/CefDetectorX#25]
![image](https://user-images.githubusercontent.com/86878459/210927921-57e5837a-b739-4ba0-bb12-461e00a81ccf.png)

**Comment by Kx-Y** [comment]
![image](https://user-images.githubusercontent.com/86878459/210928967-b5b65417-dd9d-478a-b2a6-4916b79ed35f.png)
这就很离谱

**Comment by flyzyh** [comment]
唉，我也是，everything我也有，utools搜索都能正常调用到everything，但是CEF一打开就是0个。
这是有什么配置么？
