### ISSUE TITLE
无法运行Cannot Run the program

### ISSUE THREAD

**Issue by Chinesebg** [ShirasawaSama/CefDetectorX#26]
下载完成压缩包并解压以后CefDetectorX文件**无后缀**如图：
![屏幕截图 2023-01-07 222111](https://user-images.githubusercontent.com/88040372/211155341-a1c88b66-cd9e-4108-8cc8-b7b59cb29f27.png)

无法打开。手动添加后缀后**仍无法运行**如图
![屏幕截图 2023-01-07 222250](https://user-images.githubusercontent.com/88040372/211155436-6dca9438-a171-49fe-b79d-7f7b19dd3824.png)

两个版本皆同。
最新Release

**Comment by Chinesebg** [comment]
> 建议下载0.0.4版本 新版构建好像有点问题

> 感谢！

**Comment by ShirasawaSama** [comment]
重复 #24
