### ISSUE TITLE
ffmpeg.exe 怎么 chromium 了 （恼

### ISSUE THREAD

**Issue by GregTaoo** [ShirasawaSama/CefDetectorX#28]
如题
ffmpeg.exe 成 chromium 了

**Comment by ShirasawaSama** [comment]
你点进去看那个目录下是不是又cef相关的文件，如果有的话可能是通过dll之类的形式调用cef，这种情况下检测exe不太对

**Comment by GregTaoo** [comment]
我以为是放我命令行程序文件夹里面的那个，结果是某个软件的（
