### ISSUE TITLE
不支持EleQQ(Windows)

### ISSUE THREAD

**Issue by slqwqxd** [ShirasawaSama/CefDetectorX#36]
如图，
![image](https://user-images.githubusercontent.com/109799548/229755173-a2026c76-2422-4251-9e16-7a90e0dfac34.png)
![image](https://user-images.githubusercontent.com/109799548/229755297-a7f3871a-76d0-4bb4-a9a5-e764f18b19e1.png)
然而打开安装目录
![image](https://user-images.githubusercontent.com/109799548/229755677-3b6628f5-53ad-4f2b-8ed6-7ff648d1fa08.png)
![image](https://user-images.githubusercontent.com/109799548/229755717-e0f8a0a9-2a1e-4ca5-96c6-689303ab4028.png)
是不是偷懒不检测这个了（

**Comment by ShirasawaSama** [comment]
0.1.0已经支持
