### ISSUE TITLE
高分屏布局问题

### ISSUE THREAD

**Issue by JC-ProPlus** [ShirasawaSama/CefDetectorX#7]
![图片](https://user-images.githubusercontent.com/27349962/204505365-44439d38-e386-4cf0-b12e-cf87e7a4dd00.png)
如图，这里是200%缩放

**Comment by ShirasawaSama** [comment]
electron居然有高分屏的问题吗?屏幕多大?

**Comment by JC-ProPlus** [comment]
> electron居然有高分屏的问题吗?屏幕多大?

3840*2160...但是第二遍打开又好了==

**Comment by ShirasawaSama** [comment]
那看来或许不是代码的bug(
